import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  ArrowLeft, FileText, UserCheck, Send, FlaskConical,
  CheckCircle2, AlertTriangle, Shield, Clock, Sparkles,
  Printer, ChevronDown, ChevronUp, Check, Stethoscope, Zap, TrendingUp
} from 'lucide-react';
import type { ProcessingResult, Consultation } from '../types';

interface Props {
  result: ProcessingResult;
  consultation: Consultation;
  doctor: { id: string; name: string; speciality: string; hospital: string };
}

type TabId = 'soap' | 'summary' | 'referral' | 'trials';

function ConfidenceBadge({ score }: { score: number }) {
  const config = score >= 80
    ? 'bg-emerald-50 text-emerald-700 border-emerald-200/60'
    : score >= 60
      ? 'bg-amber-50 text-amber-700 border-amber-200/60'
      : 'bg-rose-50 text-rose-700 border-rose-200/60';
  return (
    <span className={`text-xs font-semibold px-2.5 py-1 rounded-full border ${config}`}>
      {score}%
    </span>
  );
}

function ConfidenceBar({ score }: { score: number }) {
  const fill = score >= 80 ? 'from-emerald-400 to-emerald-500' : score >= 60 ? 'from-amber-400 to-amber-500' : 'from-rose-400 to-rose-500';
  return (
    <div className="h-2 rounded-full overflow-hidden bg-slate-100">
      <div className={`h-full rounded-full bg-gradient-to-r ${fill} transition-all duration-700`} style={{ width: `${score}%` }} />
    </div>
  );
}

function DisclaimerBanner() {
  return (
    <div className="flex items-start gap-3 p-4 bg-amber-50/80 border border-amber-200/60 rounded-xl mb-5">
      <Shield className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
      <p className="text-xs text-amber-800 leading-relaxed">
        <strong>AI-Generated &mdash; Requires Clinician Validation.</strong> This output was generated by AI and must be reviewed by a qualified medical professional before clinical use.
      </p>
    </div>
  );
}

function SectionApproval({ section, onApprove }: { section: string; onApprove: () => void }) {
  const [approved, setApproved] = useState(false);
  return (
    <button
      onClick={() => { setApproved(true); onApprove(); }}
      className={`flex items-center gap-1.5 text-xs px-4 py-2 rounded-xl font-semibold transition-all cursor-pointer ${
        approved
          ? 'bg-emerald-50 text-emerald-700 border border-emerald-200/60'
          : 'bg-white text-slate-600 border border-slate-200 hover:bg-emerald-50 hover:text-emerald-700 hover:border-emerald-200'
      }`}
    >
      {approved ? <Check className="w-3.5 h-3.5" /> : <CheckCircle2 className="w-3.5 h-3.5" />}
      {approved ? `${section} Approved` : `Approve ${section}`}
    </button>
  );
}

export default function ResultsPage({ result, consultation, doctor }: Props) {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<TabId>('soap');
  const [approvedSections, setApprovedSections] = useState<Set<string>>(new Set());
  const [finalized, setFinalized] = useState(false);

  const tabs: { id: TabId; label: string; icon: React.ReactNode; available: boolean }[] = [
    { id: 'soap', label: 'SOAP Note', icon: <FileText className="w-4 h-4" />, available: true },
    { id: 'summary', label: 'Patient Summary', icon: <UserCheck className="w-4 h-4" />, available: true },
    { id: 'referral', label: 'Referral Letter', icon: <Send className="w-4 h-4" />, available: !!result.referral_letter?.referral_letter },
    { id: 'trials', label: 'Trial Matches', icon: <FlaskConical className="w-4 h-4" />, available: true },
  ];

  const handleApprove = (section: string) => {
    setApprovedSections(prev => new Set([...prev, section]));
  };

  const allApproved = tabs.filter(t => t.available).every(t => approvedSections.has(t.id));
  const { soap_note: soap, patient_summary: summary, referral_letter: referral, trial_matches: trials } = result;

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-xl border-b border-slate-200/60 sticky top-0 z-20 no-print">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <button onClick={() => navigate('/')} className="p-2 hover:bg-slate-100 rounded-xl transition-all cursor-pointer">
              <ArrowLeft className="w-5 h-5 text-slate-500" />
            </button>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-medical-100 to-medical-200 text-medical-700 flex items-center justify-center font-bold text-sm">
                {consultation.patient.name.split(' ').map(n => n[0]).slice(0, 2).join('')}
              </div>
              <div>
                <h1 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                  {consultation.patient.name}
                  <span className="text-xs bg-slate-100 text-slate-600 px-2 py-0.5 rounded-lg font-medium">
                    {consultation.patient.age}y &middot; {consultation.patient.gender}
                  </span>
                </h1>
                <p className="text-xs text-slate-500">{doctor.name} &middot; {consultation.id}</p>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2.5">
            <button
              onClick={() => window.print()}
              className="flex items-center gap-1.5 text-xs text-slate-600 px-3 py-2 rounded-xl border border-slate-200 hover:bg-slate-50 transition-all cursor-pointer font-medium"
            >
              <Printer className="w-3.5 h-3.5" />
              Print
            </button>
            {finalized ? (
              <div className="flex items-center gap-1.5 text-xs bg-emerald-50 text-emerald-700 border border-emerald-200/60 px-4 py-2 rounded-xl font-semibold">
                <CheckCircle2 className="w-4 h-4" />
                Validated
              </div>
            ) : (
              <button
                onClick={() => setFinalized(true)}
                disabled={!allApproved}
                className="flex items-center gap-1.5 text-xs text-white px-4 py-2 rounded-xl font-semibold transition-all cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed shadow-md shadow-medical-600/20"
                style={{ background: allApproved ? 'linear-gradient(135deg, #0f766e 0%, #0d9488 100%)' : '#94a3b8' }}
              >
                <CheckCircle2 className="w-4 h-4" />
                Finalize All
              </button>
            )}
          </div>
        </div>

        {/* Tabs */}
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex gap-1 -mb-px overflow-x-auto">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => tab.available && setActiveTab(tab.id)}
                className={`flex items-center gap-2 px-5 py-3 text-sm font-medium border-b-2 transition-all whitespace-nowrap cursor-pointer ${
                  activeTab === tab.id
                    ? 'border-medical-600 text-medical-700'
                    : tab.available
                      ? 'border-transparent text-slate-500 hover:text-slate-700 hover:border-slate-300'
                      : 'border-transparent text-slate-300 cursor-not-allowed'
                }`}
              >
                {tab.icon}
                {tab.label}
                {approvedSections.has(tab.id) && (
                  <div className="w-4 h-4 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center">
                    <Check className="w-3 h-3" />
                  </div>
                )}
              </button>
            ))}
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        {/* SOAP Note Tab */}
        {activeTab === 'soap' && soap && (
          <div className="space-y-5">
            <DisclaimerBanner />
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-medical-50 text-medical-600 flex items-center justify-center">
                  <FileText className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-slate-900 tracking-tight">SOAP Note</h2>
                  <p className="text-xs text-slate-500">Structured clinical documentation</p>
                </div>
              </div>
              <SectionApproval section="soap" onApprove={() => handleApprove('soap')} />
            </div>

            {/* Confidence Overview */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              {Object.entries(soap.confidence_scores || {}).map(([key, score]) => (
                <div key={key} className="bg-white rounded-xl border border-slate-200/60 p-4">
                  <div className="flex items-center justify-between mb-2">
                    <p className="text-xs text-slate-500 capitalize font-medium">{key}</p>
                    <ConfidenceBadge score={score} />
                  </div>
                  <ConfidenceBar score={score} />
                </div>
              ))}
            </div>

            {/* Subjective */}
            <SOAPSection title="Subjective" subtitle="Patient-reported information" defaultOpen>
              <Field label="Chief Complaint" value={soap.subjective?.chief_complaint} highlight />
              <Field label="History of Present Illness" value={soap.subjective?.history_of_present_illness} />
              {soap.subjective?.review_of_systems && (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <ListField label="Relevant Positives" items={soap.subjective.review_of_systems.relevant_positives} variant="positive" />
                  <ListField label="Relevant Negatives" items={soap.subjective.review_of_systems.relevant_negatives} variant="negative" />
                </div>
              )}
              <ListField label="Past Medical History" items={soap.subjective?.past_medical_history} />
              <ListField label="Current Medications" items={soap.subjective?.medications} />
              <ListField label="Allergies" items={soap.subjective?.allergies} variant="warning" />
            </SOAPSection>

            {/* Objective */}
            <SOAPSection title="Objective" subtitle="Clinical findings & examination">
              {soap.objective?.vitals && (
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                  {Object.entries(soap.objective.vitals).filter(([, v]) => v && v !== 'if mentioned' && v !== 'not mentioned').map(([key, value]) => (
                    <div key={key} className="bg-medical-50/50 rounded-xl p-3 border border-medical-200/30">
                      <p className="text-[10px] text-medical-600 uppercase font-semibold tracking-wider">{key.replace(/_/g, ' ')}</p>
                      <p className="text-sm font-bold text-medical-900 mt-0.5">{value}</p>
                    </div>
                  ))}
                </div>
              )}
              <Field label="General" value={soap.objective?.physical_exam?.general} />
              {soap.objective?.physical_exam?.systems_examined?.map((sys, i) => (
                <Field key={i} label={sys.system} value={sys.findings} />
              ))}
              <ListField label="Investigations" items={soap.objective?.investigations} />
            </SOAPSection>

            {/* Assessment */}
            <SOAPSection title="Assessment" subtitle="Clinical reasoning & diagnosis">
              <Field label="Primary Diagnosis" value={soap.assessment?.primary_diagnosis} highlight />
              <ListField label="Secondary Diagnoses" items={soap.assessment?.secondary_diagnoses} />
              <Field label="Clinical Reasoning" value={soap.assessment?.clinical_reasoning} />
            </SOAPSection>

            {/* Plan */}
            <SOAPSection title="Plan" subtitle="Treatment & follow-up">
              {soap.plan?.medications_prescribed?.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Medications Prescribed</p>
                  <div className="space-y-2">
                    {soap.plan.medications_prescribed.map((med, i) => (
                      <div key={i} className="bg-medical-50/30 border border-medical-200/30 rounded-xl p-3.5">
                        <p className="text-sm font-semibold text-slate-900">{med.name}</p>
                        <div className="flex flex-wrap gap-x-4 gap-y-1 mt-1">
                          <span className="text-xs text-slate-500"><span className="font-medium text-slate-600">Dose:</span> {med.dosage}</span>
                          <span className="text-xs text-slate-500"><span className="font-medium text-slate-600">Freq:</span> {med.frequency}</span>
                          <span className="text-xs text-slate-500"><span className="font-medium text-slate-600">Duration:</span> {med.duration}</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
              <ListField label="Investigations Ordered" items={soap.plan?.investigations_ordered} />
              <ListField label="Referrals" items={soap.plan?.referrals} />
              <Field label="Follow-up" value={soap.plan?.follow_up} />
              <ListField label="Patient Education" items={soap.plan?.patient_education} />
            </SOAPSection>

            {/* Flags */}
            {soap.flags?.length > 0 && (
              <div className="bg-rose-50/80 border border-rose-200/60 rounded-2xl p-5">
                <h3 className="text-sm font-bold text-rose-700 flex items-center gap-2 mb-3">
                  <AlertTriangle className="w-4 h-4" />
                  Flags for Review
                </h3>
                <ul className="space-y-1.5">
                  {soap.flags.map((flag, i) => (
                    <li key={i} className="text-sm text-rose-700 flex items-start gap-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-rose-400 shrink-0 mt-2" />
                      {flag}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {/* Patient Summary Tab */}
        {activeTab === 'summary' && summary && (
          <div className="space-y-5">
            <DisclaimerBanner />
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-violet-50 text-violet-600 flex items-center justify-center">
                  <UserCheck className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-slate-900 tracking-tight">Patient Summary</h2>
                  <p className="text-xs text-slate-500">Plain-language visit report</p>
                </div>
              </div>
              <SectionApproval section="summary" onApprove={() => handleApprove('summary')} />
            </div>

            <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-6 sm:p-8 space-y-6">
              <p className="text-base font-medium text-slate-800 leading-relaxed">{summary.greeting}</p>

              <SummarySection title="Visit Summary" content={summary.visit_summary} />
              <SummarySection title="What the Doctor Found" content={summary.what_the_doctor_found} />

              <div className="bg-medical-50/50 border border-medical-200/30 rounded-xl p-4">
                <h3 className="text-xs font-bold text-medical-700 uppercase tracking-wider mb-1.5">Your Diagnosis</h3>
                <p className="text-sm text-medical-900 font-medium leading-relaxed">{summary.your_diagnosis}</p>
              </div>

              {/* Medications */}
              {summary.your_treatment_plan?.medications?.length > 0 && (
                <div>
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3">Your Medications</h3>
                  <div className="space-y-2.5">
                    {summary.your_treatment_plan.medications.map((med, i) => (
                      <div key={i} className="bg-slate-50/80 rounded-xl p-4 border border-slate-100">
                        <p className="text-sm font-semibold text-slate-900">{med.name}</p>
                        <p className="text-xs text-slate-500 mt-1">{med.what_its_for}</p>
                        <p className="text-xs text-medical-700 mt-1 font-medium">{med.how_to_take}</p>
                        {med.important_notes && (
                          <p className="text-xs text-amber-700 mt-1.5 bg-amber-50/80 rounded-lg px-2.5 py-1.5 border border-amber-200/40">{med.important_notes}</p>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <ListField label="Lifestyle Advice" items={summary.your_treatment_plan?.lifestyle_advice} />

              {/* Follow Up */}
              {summary.follow_up && (
                <div className="bg-medical-50/50 border border-medical-200/30 rounded-xl p-4">
                  <h3 className="text-xs font-bold text-medical-700 uppercase tracking-wider mb-2">Follow-up</h3>
                  <p className="text-sm text-medical-800 font-medium">{summary.follow_up.next_appointment}</p>
                  <ListField label="What to Bring" items={summary.follow_up.what_to_bring} />
                </div>
              )}

              {/* Warning Signs */}
              {summary.warning_signs?.length > 0 && (
                <div className="bg-rose-50/80 border border-rose-200/60 rounded-xl p-4">
                  <h3 className="text-xs font-bold text-rose-700 flex items-center gap-2 mb-2 uppercase tracking-wider">
                    <AlertTriangle className="w-3.5 h-3.5" />
                    Warning Signs - Seek Immediate Help
                  </h3>
                  <ul className="space-y-1.5">
                    {summary.warning_signs.map((sign, i) => (
                      <li key={i} className="text-sm text-rose-700 flex items-start gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-rose-400 shrink-0 mt-2" />
                        {sign}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <p className="text-xs text-slate-400 italic border-t border-slate-100 pt-4">{summary.disclaimer}</p>
            </div>
          </div>
        )}

        {/* Referral Letter Tab */}
        {activeTab === 'referral' && (
          <div className="space-y-5">
            <DisclaimerBanner />
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center">
                  <Send className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-slate-900 tracking-tight">Referral Letter</h2>
                  <p className="text-xs text-slate-500">Specialist referral documentation</p>
                </div>
              </div>
              {referral?.referral_letter && (
                <SectionApproval section="referral" onApprove={() => handleApprove('referral')} />
              )}
            </div>

            {referral?.referral_letter ? (
              <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-6 sm:p-8 space-y-6">
                {/* Letter Header */}
                <div className="border-b border-slate-200 pb-5">
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="text-sm font-bold text-slate-900">{referral.referral_letter.from}</p>
                      <p className="text-xs text-slate-500 mt-0.5">{doctor.hospital}</p>
                    </div>
                    <p className="text-xs text-slate-500 bg-slate-50 px-3 py-1.5 rounded-lg">{referral.referral_letter.date}</p>
                  </div>
                  <div className="mt-3 bg-slate-50 rounded-xl p-3">
                    <p className="text-xs text-slate-500 font-medium">To</p>
                    <p className="text-sm text-slate-800 font-semibold mt-0.5">{referral.referral_letter.to}</p>
                  </div>
                </div>

                {/* Urgency */}
                {referral.referral_letter.urgency && (
                  <div className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold ${
                    referral.referral_letter.urgency.level === 'emergent' ? 'bg-rose-50 text-rose-700 border border-rose-200/60' :
                    referral.referral_letter.urgency.level === 'urgent' ? 'bg-amber-50 text-amber-700 border border-amber-200/60' :
                    'bg-emerald-50 text-emerald-700 border border-emerald-200/60'
                  }`}>
                    <AlertTriangle className="w-3.5 h-3.5" />
                    {referral.referral_letter.urgency.level?.toUpperCase()} - {referral.referral_letter.urgency.reasoning}
                  </div>
                )}

                <Field label="Reason for Referral" value={referral.referral_letter.reason_for_referral} highlight />
                <Field label="Patient" value={referral.referral_letter.patient_summary?.demographics} />
                <Field label="Presenting Complaint" value={referral.referral_letter.patient_summary?.presenting_complaint} />
                <Field label="Current Condition" value={referral.referral_letter.relevant_history?.current_condition} />
                <ListField label="Relevant Past History" items={referral.referral_letter.relevant_history?.relevant_past_history} />
                <ListField label="Current Medications" items={referral.referral_letter.relevant_history?.current_medications} />

                {referral.referral_letter.investigations && (
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                    <ListField label="Completed" items={referral.referral_letter.investigations.completed} variant="positive" />
                    <ListField label="Pending" items={referral.referral_letter.investigations.pending} variant="warning" />
                    <ListField label="Recommended Before Visit" items={referral.referral_letter.investigations.recommended_before_visit} />
                  </div>
                )}

                <ListField label="Clinical Questions for Specialist" items={referral.referral_letter.clinical_questions} />
                <ListField label="Patient Preparation Checklist" items={referral.referral_letter.patient_preparation_checklist} />

                <div className="flex items-center gap-3 pt-4 border-t border-slate-100">
                  <span className="text-xs text-slate-500 font-medium">Confidence:</span>
                  <ConfidenceBadge score={referral.confidence_score} />
                </div>
              </div>
            ) : (
              <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-12 text-center">
                <Send className="w-8 h-8 text-slate-300 mx-auto mb-3" />
                <p className="text-slate-500 font-medium">No referral indicated for this consultation.</p>
              </div>
            )}
          </div>
        )}

        {/* Trial Matches Tab */}
        {activeTab === 'trials' && trials && (
          <div className="space-y-5">
            <DisclaimerBanner />
            <div className="bg-blue-50/80 border border-blue-200/60 rounded-xl p-4 flex items-start gap-3">
              <Zap className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
              <p className="text-xs text-blue-800 leading-relaxed">
                <strong>INFORMATIONAL ONLY:</strong> {trials.disclaimer || 'These are potential eligibility signals, not enrollment recommendations. Physician review and patient consent are always required.'}
              </p>
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-purple-50 text-purple-600 flex items-center justify-center">
                  <FlaskConical className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-slate-900 tracking-tight">Clinical Trial Matches</h2>
                  <p className="text-xs text-slate-500">RAG-powered trial search via Bedrock Knowledge Bases</p>
                </div>
              </div>
              <SectionApproval section="trials" onApprove={() => handleApprove('trials')} />
            </div>

            {trials.summary && (
              <p className="text-sm text-slate-600 bg-white rounded-xl border border-slate-200/60 p-4 leading-relaxed">{trials.summary}</p>
            )}

            {trials.trial_matches?.length > 0 ? (
              <div className="space-y-4">
                {trials.trial_matches
                  .filter(t => t.confidence_score >= 60)
                  .sort((a, b) => b.confidence_score - a.confidence_score)
                  .map((trial, i) => (
                  <div key={i} className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-5 hover:shadow-md transition-shadow duration-300">
                    <div className="flex items-start justify-between mb-3">
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="text-xs font-mono bg-slate-100 text-slate-600 px-2.5 py-1 rounded-lg font-semibold">{trial.trial_id}</span>
                          <span className="text-xs bg-purple-50 text-purple-700 border border-purple-200/60 px-2.5 py-1 rounded-lg font-medium">{trial.trial_phase}</span>
                          <span className={`text-xs px-2.5 py-1 rounded-lg font-medium border ${
                            trial.enrollment_status === 'Recruiting' ? 'bg-emerald-50 text-emerald-700 border-emerald-200/60' : 'bg-slate-50 text-slate-600 border-slate-200/60'
                          }`}>{trial.enrollment_status}</span>
                        </div>
                        <h3 className="text-sm font-semibold text-slate-900 mt-2.5 leading-relaxed">{trial.trial_title}</h3>
                        <p className="text-xs text-slate-500 mt-1">{trial.sponsor}</p>
                      </div>
                      <div className="ml-4 shrink-0">
                        <ConfidenceBadge score={trial.confidence_score} />
                      </div>
                    </div>

                    {/* Criteria */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-4">
                      {trial.matched_criteria?.length > 0 && (
                        <div className="bg-emerald-50/50 rounded-xl p-3.5 border border-emerald-200/30">
                          <p className="text-xs font-bold text-emerald-700 uppercase tracking-wider mb-2">Matched Criteria</p>
                          <div className="space-y-1.5">
                            {trial.matched_criteria.map((c, j) => (
                              <div key={j} className="text-xs flex items-start gap-1.5">
                                <Check className="w-3.5 h-3.5 text-emerald-500 shrink-0 mt-0.5" />
                                <span className="text-emerald-800">{c.criterion}: {c.patient_value}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                      {trial.unmatched_criteria?.length > 0 && (
                        <div className="bg-rose-50/50 rounded-xl p-3.5 border border-rose-200/30">
                          <p className="text-xs font-bold text-rose-700 uppercase tracking-wider mb-2">Unmatched Criteria</p>
                          <div className="space-y-1.5">
                            {trial.unmatched_criteria.map((c, j) => (
                              <div key={j} className="text-xs text-rose-800">
                                {c.criterion}: {c.patient_value} (required: {c.required_value})
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>

                    {trial.missing_information?.length > 0 && (
                      <p className="text-xs text-slate-500 mt-3 bg-slate-50 rounded-lg px-3 py-2">
                        <span className="font-medium">Missing info:</span> {trial.missing_information.join(', ')}
                      </p>
                    )}

                    {trial.locations?.length > 0 && (
                      <div className="mt-3 pt-3 border-t border-slate-100">
                        <p className="text-xs text-slate-500">
                          <span className="font-medium">Locations:</span> {trial.locations.join(' | ')}
                        </p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            ) : (
              <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-12 text-center">
                <FlaskConical className="w-8 h-8 text-slate-300 mx-auto mb-3" />
                <p className="text-slate-500 font-medium">No matching clinical trials found with sufficient confidence.</p>
              </div>
            )}
          </div>
        )}

        {/* Processing Metadata */}
        <div className="mt-8 bg-white rounded-2xl border border-slate-200/60 shadow-sm p-5 no-print">
          <h3 className="text-sm font-bold text-slate-700 mb-4 flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-medical-500" />
            AI Processing Details
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {result.processing_steps?.map((step, i) => (
              <div key={i} className="bg-slate-50 rounded-xl p-3">
                <p className="text-xs text-slate-500 font-medium">{step.step}</p>
                <p className="text-sm font-semibold text-slate-800 flex items-center gap-1 mt-1">
                  <Clock className="w-3 h-3 text-medical-500" />
                  {(step.duration_ms / 1000).toFixed(1)}s
                </p>
              </div>
            ))}
          </div>
          <div className="flex flex-wrap items-center gap-4 mt-4 pt-4 border-t border-slate-100 text-xs text-slate-400">
            <span className="flex items-center gap-1"><Stethoscope className="w-3 h-3" /> {result.metadata?.model_used}</span>
            <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> {((result.metadata?.total_processing_time_ms || 0) / 1000).toFixed(1)}s total</span>
            <span className="flex items-center gap-1"><TrendingUp className="w-3 h-3" /> {result.metadata?.version}</span>
            {result.metadata?.architecture && <span className="flex items-center gap-1"><Zap className="w-3 h-3" /> {result.metadata.architecture}</span>}
          </div>
        </div>
      </main>
    </div>
  );
}

// ─── Reusable Sub-components ─────────────────────────────────

function SOAPSection({ title, subtitle, children, defaultOpen = false }: { title: string; subtitle?: string; children: React.ReactNode; defaultOpen?: boolean }) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between p-5 hover:bg-slate-50/50 transition-colors cursor-pointer"
      >
        <div>
          <h3 className="text-sm font-bold text-slate-900">{title}</h3>
          {subtitle && <p className="text-xs text-slate-500 mt-0.5">{subtitle}</p>}
        </div>
        <div className="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center">
          {open ? <ChevronUp className="w-4 h-4 text-slate-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
        </div>
      </button>
      {open && <div className="px-5 pb-5 space-y-4 border-t border-slate-100 pt-4">{children}</div>}
    </div>
  );
}

function SummarySection({ title, content }: { title: string; content?: string }) {
  if (!content) return null;
  return (
    <div>
      <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1.5">{title}</h3>
      <p className="text-sm text-slate-700 leading-relaxed">{content}</p>
    </div>
  );
}

function Field({ label, value, highlight }: { label: string; value?: string; highlight?: boolean }) {
  if (!value) return null;
  return (
    <div>
      <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">{label}</p>
      {highlight ? (
        <p className="text-sm font-medium text-medical-800 bg-medical-50/50 p-3 rounded-xl border border-medical-200/30 leading-relaxed">{value}</p>
      ) : (
        <p className="text-sm text-slate-700 leading-relaxed">{value}</p>
      )}
    </div>
  );
}

function ListField({ label, items, variant }: { label: string; items?: string[]; variant?: 'positive' | 'negative' | 'warning' }) {
  if (!items || items.length === 0) return null;
  const dotColor = variant === 'positive' ? 'bg-emerald-400' : variant === 'negative' ? 'bg-slate-400' : variant === 'warning' ? 'bg-amber-400' : 'bg-slate-400';
  return (
    <div>
      <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1.5">{label}</p>
      <ul className="space-y-1">
        {items.map((item, i) => (
          <li key={i} className="text-sm text-slate-700 flex items-start gap-2">
            <span className={`w-1.5 h-1.5 rounded-full ${dotColor} shrink-0 mt-2`} />
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}
